### ISSUE TITLE
Default closure relation should be isa/partof

### ISSUE THREAD

**Issue by kltm** [geneontology/biolink-api#30]
In the biolink-api ontology_endpoint (https://github.com/geneontology/biolink-api/blob/a2d6553378ed13881247da04fb0b123871c841ef/biolink/api/ontol/endpoints/ontology_endpoint.py), "isa_partof" seems to be the default in OntologyTermsSharedAncestor(Resource)
https://github.com/geneontology/biolink-api/blob/a2d6553378ed13881247da04fb0b123871c841ef/biolink/api/ontol/endpoints/ontology_endpoint.py#L266

OntologyRibbons(Resource) seems to hardcode to "regulates".

Looking around the variable `cross_aspect` and elsewhere, "regulates_closure" appears to be completely hardcoded, without possibility of override, at least four times. However, what that code is used for is a little bit unclear to me.

Looking at lines like 29
`related_params.add_argument('relationship_type', choices=[IS_A, IS_A_PART_OF, REGULATES], default=IS_A_PART_OF, help="relationship type ('{}', '{}' or '{}')".format(IS_A, IS_A_PART_OF, REGULATES))`
It seems that "isa_partof" may be the default when the choice is possible/coded for.

There is no choice for transitivity graph apparently:
https://github.com/geneontology/biolink-api/blob/a2d6553378ed13881247da04fb0b123871c841ef/biolink/api/ontol/endpoints/ontology_endpoint.py#L32

When originally coded, the choice was known and different cases were actively hardcoded. Now that the GO has switched from the default "regulates" to the default "isa_partof", we should probably revisit this code and make sure that we're doing the right thing for our consumers (and that it is documented).

**Comment by kltm** [comment]
Noting that this may practically be best handled once we've done a little more refactoring (in progress w/@sierra-moxon) and have more control of the GO API.

**Comment by cmungall** [comment]
The default relation for propagating should be is-a/part-of in solr

**Comment by cmungall** [comment]
What remains to be done? I thought we made is-a/part-of the closure a long time ago? Can we close?
