### ISSUE TITLE
[Proposal] Integrate GO-CAM routes in the GO API

### ISSUE THREAD

**Issue by lpalbou** [geneontology/biolink-api#5]
The public GO-CAM site is still powered by the https://api.geneontology.cloud API Gateway/AWS Lambda (https://github.com/geneontology/api-gorest) which is essentially a HTTPS proxy with pre-formated queries to the **non HTTPS** SPARQL endpoint http://rdf.geneontology.org. Although this has worked without any issue and has its own CI/CD, the useful routes should be merged back to the GO API. The swagger of the GO-CAM API with currently working routes are here: https://app.swaggerhub.com/apis-docs/geneontology/gosparql

Since many of those routes have been re-implemented on the Minerva API, they are now only relevant to the public GO-CAM site and to external users. They could be used also in the interactive notebooks planned for GO.

**Proposal**:
* integrate the SPARQL queries directly to the GO BioLink API, essentially serving as a proxy to the RDF endpoint
* create the long desired SPARQLr format (parser + socket library in python) to launch preformated SPARQL queries with customizable parameters. Then integrate this library to GO BioLink API to serve the GO-CAM route. Pros: reusable library, common place to store SPARQL queries. Cons: longer to develop

**Preference**:
* SPARQLr seems like a good idea for a long time. The manual sharing of SPARQL queries to a triple store without schema was limiting to many developers in the group and is probably opaque to most external developers. Having SPARQLr to handle those GO-CAM queries would ease their use and at the same time the understanding of the underlying triple store. 

**Notes**:
* The SPARQLr option could serve as a replacement for GOOSE too and would be useful to power interactive notebooks and web UIs
* A preliminary integration was done on the /cam routes of http://api.geneontology.org/api/

**Comment by deepakunni3** [comment]
Full payload and minimized payload (this is different from compact_associations).
The latter is more of an optimized data structure focused on removing redundancy and verbosity.

**Comment by kltm** [comment]
Different project, largely completed.
